import { Intent } from "@blueprintjs/core";
import type { PDFDiffProject } from "./pdfDiffTypes";

export const sampleContractDiff: PDFDiffProject = {
  title: "X52 Enterprise Master Service Agreement (MSA)",
  diffItems: [
    {
      id: "diff-01",
      pageNumber: 1,
      paragraphIndex: 3,
      lineNumber: 4,
      section: "Section 2.1: Annual License Fees",
      category: "FINANCIAL",
      severity: "HIGH",
      intent: Intent.DANGER,
      title: "Subscription Pricing Increased by $25,000 / yr",
      description: "Base recurring licensing fee was increased from $120,000/yr to $145,000/yr with an automatic 5% annual escalator.",
      preText: "2.1 Annual subscription license fee shall be fixed at $120,000 USD payable quarterly in advance without automatic escalator.",
      postText: "2.1 Annual subscription license fee shall be fixed at $145,000 USD payable quarterly in advance, subject to a 5% annual increase.",
      changeType: "MODIFIED",
    },
    {
      id: "diff-02",
      pageNumber: 1,
      paragraphIndex: 5,
      lineNumber: 8,
      section: "Section 4.3: Service Level Agreement (SLA)",
      category: "SLA_CLAUSE",
      severity: "HIGH",
      intent: Intent.DANGER,
      title: "SLA Uptime Guarantee Lowered to 99.5%",
      description: "Service commitment reduced from 99.99% high availability down to 99.5%, excluding scheduled maintenance windows.",
      preText: "4.3 Provider guarantees a 99.99% monthly system uptime SLA, backed by 15% service fee credits for non-compliance.",
      postText: "4.3 Provider guarantees a 99.5% monthly system uptime SLA, backed by 5% service fee credits for non-compliance.",
      changeType: "MODIFIED",
    },
    {
      id: "diff-03",
      pageNumber: 1,
      paragraphIndex: 7,
      lineNumber: 12,
      section: "Section 6.2: Data Ingestion & Bandwidth Cap",
      category: "METRIC",
      severity: "MEDIUM",
      intent: Intent.PRIMARY,
      title: "Throughput Quota Raised to 250 GB/s",
      description: "Monthly cluster bandwidth quota increased to accommodate expanded Foundry pipeline ingestion.",
      preText: "6.2 Telemetry ingestion bandwidth quota is capped at 100 GB/s aggregate throughput across all active partitions.",
      postText: "6.2 Telemetry ingestion bandwidth quota is capped at 250 GB/s aggregate throughput across all active partitions.",
      changeType: "MODIFIED",
    },
    {
      id: "diff-04",
      pageNumber: 2,
      paragraphIndex: 2,
      lineNumber: 3,
      section: "Section 8.4: Limitation of Liability",
      category: "LEGAL_RISK",
      severity: "HIGH",
      intent: Intent.DANGER,
      title: "Liability Cap Reduced from 3x to 1x Annual Fees",
      description: "Maximum aggregate indemnification liability ceiling significantly lowered from 300% down to 100% of fees paid.",
      preText: "8.4 In no event shall either party's aggregate liability exceed three times (3x) the total fees paid in the preceding 12 months.",
      postText: "8.4 In no event shall either party's aggregate liability exceed one times (1x) the total fees paid in the preceding 12 months.",
      changeType: "MODIFIED",
    },
    {
      id: "diff-05",
      pageNumber: 2,
      paragraphIndex: 4,
      lineNumber: 7,
      section: "Section 11.1: Termination for Convenience",
      category: "DATE_TERMS",
      severity: "MEDIUM",
      intent: Intent.WARNING,
      title: "Notice Window Extended from 30 to 90 Days",
      description: "Termination notice period tripled, requiring at least 90 calendar days prior written notice.",
      preText: "11.1 Either party may terminate this agreement without cause upon thirty (30) days prior written notice.",
      postText: "11.1 Either party may terminate this agreement without cause upon ninety (90) days prior written notice.",
      changeType: "MODIFIED",
    },
  ],
  preDocument: {
    fileName: "X52_MSA_Agreement_Original_v1.2.pdf",
    fileSize: "2.4 MB",
    version: "Original (Pre-Change)",
    uploadedAt: "2026-08-10",
    totalPages: 2,
    pages: [
      {
        pageNumber: 1,
        paragraphs: [
          {
            id: "p-pre-1-1",
            paragraphIndex: 1,
            text: "X52 ENTERPRISE PLATFORM MASTER SERVICE AGREEMENT",
            diffType: "UNCHANGED",
          },
          {
            id: "p-pre-1-2",
            paragraphIndex: 2,
            text: "This agreement is entered into as of the Effective Date by and between X52 Corp and Enterprise Customer. The terms and conditions herein govern the provision, deployment, and operation of dedicated 52-node compute clusters and telemetry streaming infrastructure.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-pre-1-3",
            paragraphIndex: 3,
            text: "2.1 Annual subscription license fee shall be fixed at $120,000 USD payable quarterly in advance without automatic escalator.",
            diffId: "diff-01",
            diffType: "MODIFIED",
            severity: "HIGH",
            category: "FINANCIAL",
            diffTitle: "Subscription Pricing Increased by $25,000 / yr",
          },
          {
            id: "p-pre-1-4",
            paragraphIndex: 4,
            text: "3.1 All hardware compute cluster resources (52 dedicated physical nodes) remain exclusive to the customer environment with zero multi-tenant resource contention.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-pre-1-5",
            paragraphIndex: 5,
            text: "4.3 Provider guarantees a 99.99% monthly system uptime SLA, backed by 15% service fee credits for non-compliance.",
            diffId: "diff-02",
            diffType: "MODIFIED",
            severity: "HIGH",
            category: "SLA_CLAUSE",
            diffTitle: "SLA Uptime Guarantee Lowered to 99.5%",
          },
          {
            id: "p-pre-1-6",
            paragraphIndex: 6,
            text: "5.1 Dedicated support response times are guaranteed within fifteen (15) minutes for Critical Severity 1 incidents with 24/7/365 global Tier-3 escalation protocols.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-pre-1-7",
            paragraphIndex: 7,
            text: "6.2 Telemetry ingestion bandwidth quota is capped at 100 GB/s aggregate throughput across all active partitions.",
            diffId: "diff-03",
            diffType: "MODIFIED",
            severity: "MEDIUM",
            category: "METRIC",
            diffTitle: "Throughput Quota Raised to 250 GB/s",
          },
        ],
      },
      {
        pageNumber: 2,
        paragraphs: [
          {
            id: "p-pre-2-1",
            paragraphIndex: 1,
            text: "SECTION 8: CONFIDENTIALITY & LIABILITY LIMITS",
            diffType: "UNCHANGED",
          },
          {
            id: "p-pre-2-2",
            paragraphIndex: 2,
            text: "8.4 In no event shall either party's aggregate liability exceed three times (3x) the total fees paid in the preceding 12 months.",
            diffId: "diff-04",
            diffType: "MODIFIED",
            severity: "HIGH",
            category: "LEGAL_RISK",
            diffTitle: "Liability Cap Reduced from 3x to 1x Annual Fees",
          },
          {
            id: "p-pre-2-3",
            paragraphIndex: 3,
            text: "9.1 Mutual indemnification covers third-party intellectual property infringement claims and regulatory compliance attestation.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-pre-2-4",
            paragraphIndex: 4,
            text: "11.1 Either party may terminate this agreement without cause upon thirty (30) days prior written notice.",
            diffId: "diff-05",
            diffType: "MODIFIED",
            severity: "MEDIUM",
            category: "DATE_TERMS",
            diffTitle: "Notice Window Extended from 30 to 90 Days",
          },
          {
            id: "p-pre-2-5",
            paragraphIndex: 5,
            text: "IN WITNESS WHEREOF, the parties hereto have executed this Agreement by their duly authorized representatives as of the date first written above.",
            diffType: "UNCHANGED",
          },
        ],
      },
    ],
  },
  postDocument: {
    fileName: "X52_MSA_Agreement_Revised_v1.3.pdf",
    fileSize: "2.5 MB",
    version: "Revised (Post-Change)",
    uploadedAt: "2026-08-22",
    totalPages: 2,
    pages: [
      {
        pageNumber: 1,
        paragraphs: [
          {
            id: "p-post-1-1",
            paragraphIndex: 1,
            text: "X52 ENTERPRISE PLATFORM MASTER SERVICE AGREEMENT",
            diffType: "UNCHANGED",
          },
          {
            id: "p-post-1-2",
            paragraphIndex: 2,
            text: "This agreement is entered into as of the Effective Date by and between X52 Corp and Enterprise Customer. The terms and conditions herein govern the provision, deployment, and operation of dedicated 52-node compute clusters and telemetry streaming infrastructure.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-post-1-3",
            paragraphIndex: 3,
            text: "2.1 Annual subscription license fee shall be fixed at $145,000 USD payable quarterly in advance, subject to a 5% annual increase.",
            diffId: "diff-01",
            diffType: "MODIFIED",
            severity: "HIGH",
            category: "FINANCIAL",
            diffTitle: "Subscription Pricing Increased by $25,000 / yr",
          },
          {
            id: "p-post-1-4",
            paragraphIndex: 4,
            text: "3.1 All hardware compute cluster resources (52 dedicated physical nodes) remain exclusive to the customer environment with zero multi-tenant resource contention.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-post-1-5",
            paragraphIndex: 5,
            text: "4.3 Provider guarantees a 99.5% monthly system uptime SLA, backed by 5% service fee credits for non-compliance.",
            diffId: "diff-02",
            diffType: "MODIFIED",
            severity: "HIGH",
            category: "SLA_CLAUSE",
            diffTitle: "SLA Uptime Guarantee Lowered to 99.5%",
          },
          {
            id: "p-post-1-6",
            paragraphIndex: 6,
            text: "5.1 Dedicated support response times are guaranteed within fifteen (15) minutes for Critical Severity 1 incidents with 24/7/365 global Tier-3 escalation protocols.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-post-1-7",
            paragraphIndex: 7,
            text: "6.2 Telemetry ingestion bandwidth quota is capped at 250 GB/s aggregate throughput across all active partitions.",
            diffId: "diff-03",
            diffType: "MODIFIED",
            severity: "MEDIUM",
            category: "METRIC",
            diffTitle: "Throughput Quota Raised to 250 GB/s",
          },
        ],
      },
      {
        pageNumber: 2,
        paragraphs: [
          {
            id: "p-post-2-1",
            paragraphIndex: 1,
            text: "SECTION 8: CONFIDENTIALITY & LIABILITY LIMITS",
            diffType: "UNCHANGED",
          },
          {
            id: "p-post-2-2",
            paragraphIndex: 2,
            text: "8.4 In no event shall either party's aggregate liability exceed one times (1x) the total fees paid in the preceding 12 months.",
            diffId: "diff-04",
            diffType: "MODIFIED",
            severity: "HIGH",
            category: "LEGAL_RISK",
            diffTitle: "Liability Cap Reduced from 3x to 1x Annual Fees",
          },
          {
            id: "p-post-2-3",
            paragraphIndex: 3,
            text: "9.1 Mutual indemnification covers third-party intellectual property infringement claims and regulatory compliance attestation.",
            diffType: "UNCHANGED",
          },
          {
            id: "p-post-2-4",
            paragraphIndex: 4,
            text: "11.1 Either party may terminate this agreement without cause upon ninety (90) days prior written notice.",
            diffId: "diff-05",
            diffType: "MODIFIED",
            severity: "MEDIUM",
            category: "DATE_TERMS",
            diffTitle: "Notice Window Extended from 30 to 90 Days",
          },
          {
            id: "p-post-2-5",
            paragraphIndex: 5,
            text: "IN WITNESS WHEREOF, the parties hereto have executed this Agreement by their duly authorized representatives as of the date first written above.",
            diffType: "UNCHANGED",
          },
        ],
      },
    ],
  },
};
